name: CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag name"
        required: true
        type: string
      no_release:
        description: "no_release"
        required: true
        type: boolean

  push:
    # Triggers on every tag starting with v
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update package lists
        run: sudo apt update

      - name: Install libfdt-dev, cmake and cross toolchain
        run: sudo apt install libfdt-dev cmake squashfs-tools gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu

      - name: Run builder script
        run: |
          mkdir -m 0700 $HOME/.gnupg
          bash build_installer.sh

      - name: upload-artifact - images
        uses: actions/upload-artifact@v4
        with:
          name: images
          path: "*.*i*"

  release:
    if: inputs.no_release == '0'
    needs: build
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      # https://cli.github.com/manual/gh_release_create
      - name: Create Release
        run: gh release create ${{ inputs.tag || github.ref_name }}

      # https://cli.github.com/manual/gh_release_upload
      - name: Upload assets
        run: gh release upload ${{ inputs.tag || github.ref_name }} images/*.*i* --clobber
